dist: xenial
install: gem install rubocop
script: rubocop --except Style/FrozenStringLiteralComment
notifications:
  email: false
  slack:
    secure: D77lJjAaD+qaXFh0EK5SRJju5Jt+/q2AHYOS8hj9J209Ccb79LDx1+Hg4Ff5HSPr51FhBK6YTobc2buwzuLUBU1KmdTaSKJr5vna2V5hqJpkdQX6k5nt7bXaMEHqu8rN2T8+NXn59SbEKVU6UHzVLbZVFK9vyEgl/r968b5l/QzsAh8pE9TztRVu0pSxC74rCSjzJcwf0U03aA9qQiTasPtP9tvnqjH0ABSeqf1HvUdFNaxTTnsgF5wI/VGfy5d3ub4X4TEFe7G1fGdiao1uV0byce1ABVg8sh/R4DddiCroJm1hJdDon7PogFvoB9GfPA0oo6FIsvCsz8SZY7ytCCOKIBEWiOTK3HsAZ2OMIiBsDa+5J58N3r61e1JgdI6XTg+DhqVnMr2WNZXo0fujCpz7UE9IX7wypzY511sTQBId3IfF7ebXfQMw0tSgwrswcOsEbLFX51+V87e/cDHtcdpH3ZB+oXewHt5WpAgc7kQOj2Mh8e97KTmXL2Uw5Q88dQG+HLpke8Zu0Wb+zZ6Aw7M3J1r/ga+qPn+URYBGsdowjqpHjXYMvdCJJEp1vAl2MIXX/kS1mHatL5MHmnk92DDOjD/+HaKust3b57wyn5ogcV+Dkq9LxvsP8sIlYC76L2t9irDQprOcV7nV+5lhTB5pt7g62WBWSeAQ/eRo/v4=
